/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package windows;

/**
 *
 * @author Diego
 */
public class Combat extends javax.swing.JFrame {

    /**
     * Creates new form Combat
     */
    public Combat() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nerite = new javax.swing.JLabel();
        hakonmyo = new javax.swing.JLabel();
        attack1 = new javax.swing.JButton();
        attack2 = new javax.swing.JButton();
        attack3 = new javax.swing.JButton();
        attack4 = new javax.swing.JButton();
        giveUp = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nerite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/NeriteP1.png"))); // NOI18N
        getContentPane().add(nerite, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 320, 250));

        hakonmyo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Hakonmyo.png"))); // NOI18N
        getContentPane().add(hakonmyo, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 90, 260, 270));

        attack1.setText("jButton1");
        attack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attack1ActionPerformed(evt);
            }
        });
        getContentPane().add(attack1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 500, 220, 80));

        attack2.setText("jButton2");
        attack2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attack2ActionPerformed(evt);
            }
        });
        getContentPane().add(attack2, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 500, 220, 80));

        attack3.setText("jButton3");
        attack3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attack3ActionPerformed(evt);
            }
        });
        getContentPane().add(attack3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 580, 220, 80));

        attack4.setText("jButton4");
        attack4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attack4ActionPerformed(evt);
            }
        });
        getContentPane().add(attack4, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 580, 220, 80));

        giveUp.setBackground(new java.awt.Color(0, 0, 0));
        giveUp.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        giveUp.setForeground(new java.awt.Color(255, 255, 0));
        giveUp.setText("GIVE UP");
        giveUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                giveUpActionPerformed(evt);
            }
        });
        getContentPane().add(giveUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        exit.setBackground(new java.awt.Color(255, 0, 0));
        exit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        exit.setText("EXIT");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 10, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Background.jpg"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void giveUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_giveUpActionPerformed
        Defeat window = new Defeat();
        window.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_giveUpActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void attack4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attack4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_attack4ActionPerformed

    private void attack3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attack3ActionPerformed
        
    }//GEN-LAST:event_attack3ActionPerformed

    private void attack2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attack2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_attack2ActionPerformed

    private void attack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attack1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_attack1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Combat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Combat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Combat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Combat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Combat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton attack1;
    private javax.swing.JButton attack2;
    private javax.swing.JButton attack3;
    private javax.swing.JButton attack4;
    private javax.swing.JLabel background;
    private javax.swing.JButton exit;
    private javax.swing.JButton giveUp;
    private javax.swing.JLabel hakonmyo;
    private javax.swing.JLabel nerite;
    // End of variables declaration//GEN-END:variables
}
