/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package windows;

import classpackage.Battle;

/**
 *
 * @author Diego
 */
public class Combat extends javax.swing.JFrame {

    /**
     * Creates new form Combat
     */
    public Combat() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nerite = new javax.swing.JLabel();
        hakonmyo = new javax.swing.JLabel();
        attack1 = new javax.swing.JButton();
        attack2 = new javax.swing.JButton();
        attack3 = new javax.swing.JButton();
        attack4 = new javax.swing.JButton();
        giveUp = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        mLHP = new javax.swing.JLabel();
        rLHP = new javax.swing.JLabel();
        rHP = new javax.swing.JLabel();
        hakonmyoname = new javax.swing.JLabel();
        myHp = new javax.swing.JLabel();
        neriteName = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nerite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/NeriteP1.png"))); // NOI18N
        getContentPane().add(nerite, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 320, 250));

        hakonmyo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Hakonmyo.png"))); // NOI18N
        getContentPane().add(hakonmyo, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 90, 260, 270));

        attack1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        attack1.setText("Water Gun");
        attack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attack1ActionPerformed(evt);
            }
        });
        getContentPane().add(attack1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 500, 220, 80));

        attack2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        attack2.setText("Hydro Pump");
        attack2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attack2ActionPerformed(evt);
            }
        });
        getContentPane().add(attack2, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 500, 220, 80));

        attack3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        attack3.setText("Water Pulse");
        attack3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attack3ActionPerformed(evt);
            }
        });
        getContentPane().add(attack3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 580, 220, 80));

        attack4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        attack4.setText("Iron Tail");
        attack4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attack4ActionPerformed(evt);
            }
        });
        getContentPane().add(attack4, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 580, 220, 80));

        giveUp.setBackground(new java.awt.Color(0, 0, 0));
        giveUp.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        giveUp.setForeground(new java.awt.Color(255, 255, 0));
        giveUp.setText("GIVE UP");
        giveUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                giveUpActionPerformed(evt);
            }
        });
        getContentPane().add(giveUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        exit.setBackground(new java.awt.Color(255, 0, 0));
        exit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        exit.setText("EXIT");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 10, -1, -1));

        mLHP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mLHP.setText("190");
        getContentPane().add(mLHP, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 518, 30, 20));

        rLHP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rLHP.setText("160");
        getContentPane().add(rLHP, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, -1, -1));

        rHP.setBackground(new java.awt.Color(255, 255, 255));
        rHP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rHP.setText("/160");
        rHP.setOpaque(true);
        getContentPane().add(rHP, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 70, 60));

        hakonmyoname.setBackground(new java.awt.Color(255, 255, 255));
        hakonmyoname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        hakonmyoname.setText("Hakonmyo");
        hakonmyoname.setOpaque(true);
        getContentPane().add(hakonmyoname, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 200, 80));

        myHp.setBackground(new java.awt.Color(255, 255, 255));
        myHp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        myHp.setText("/190");
        myHp.setOpaque(true);
        getContentPane().add(myHp, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 500, 80, 60));

        neriteName.setBackground(new java.awt.Color(255, 255, 255));
        neriteName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        neriteName.setText("Nerite");
        neriteName.setOpaque(true);
        getContentPane().add(neriteName, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 500, 200, 80));

        background.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Background.jpg"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void giveUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_giveUpActionPerformed
        Defeat window = new Defeat();
        window.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_giveUpActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void attack4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attack4ActionPerformed
        combat.fight(30, enemyDamage());
        endBattle(combat.isVictory(),combat.isDefeat());
        mLHP.setText(String.valueOf(combat.getMyLostHP()));
        rLHP.setText(String.valueOf(combat.getrLostHP()));
    }//GEN-LAST:event_attack4ActionPerformed

    private void attack3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attack3ActionPerformed
        combat.fight(40, enemyDamage());
        endBattle(combat.isVictory(),combat.isDefeat());
        mLHP.setText(String.valueOf(combat.getMyLostHP()));
        rLHP.setText(String.valueOf(combat.getrLostHP()));
    }//GEN-LAST:event_attack3ActionPerformed

    private void attack2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attack2ActionPerformed
        combat.fight(45, enemyDamage());
        endBattle(combat.isVictory(),combat.isDefeat());
        mLHP.setText(String.valueOf(combat.getMyLostHP()));
        rLHP.setText(String.valueOf(combat.getrLostHP()));
    }//GEN-LAST:event_attack2ActionPerformed

    private void attack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attack1ActionPerformed
        combat.fight(25, enemyDamage());
        endBattle(combat.isVictory(),combat.isDefeat());
        mLHP.setText(String.valueOf(combat.getMyLostHP()));
        rLHP.setText(String.valueOf(combat.getrLostHP()));
    }//GEN-LAST:event_attack1ActionPerformed

    Battle combat = new Battle(190,45,28,160,36,25);
    public void endBattle(boolean v, boolean d){
        if(v==true){
            Victory window = new Victory();
            window.setVisible(true);
            this.setVisible(false);
        }
        if(d==true){
            Defeat window = new Defeat();
            window.setVisible(true);
            this.setVisible(false);
        }
    }
    
    public int enemyDamage(){
        int select, damage = 0;
        do{
            select = (int)(Math.random()*10);
        }while(select>3);
        switch(select){
            case 0: damage = 45;
                    break;
            case 1: damage = 35;
                    break;
            case 2: damage = 50;
                    break;
            case 3: damage = 45;
                    break;
        }
        return damage;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Combat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Combat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Combat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Combat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Combat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton attack1;
    private javax.swing.JButton attack2;
    private javax.swing.JButton attack3;
    private javax.swing.JButton attack4;
    private javax.swing.JLabel background;
    private javax.swing.JButton exit;
    private javax.swing.JButton giveUp;
    private javax.swing.JLabel hakonmyo;
    private javax.swing.JLabel hakonmyoname;
    private javax.swing.JLabel mLHP;
    private javax.swing.JLabel myHp;
    private javax.swing.JLabel nerite;
    private javax.swing.JLabel neriteName;
    private javax.swing.JLabel rHP;
    private javax.swing.JLabel rLHP;
    // End of variables declaration//GEN-END:variables
}
